apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.service.image.version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: {{ .Chart.Name}}
          imagePullPolicy: Always
          image: {{ .Values.service.image.name }}:{{ .Values.service.image.version }}
          
          livenessProbe:
            httpGet:
                port: {{ .Values.service.port }}
                path: /manage/health
            periodSeconds: 20
          resources:
            requests:
              cpu: "{{ .Values.service.resources.requests.cpu }}"
              memory: "{{ .Values.service.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.service.resources.limits.cpu }}"
              memory: "{{ .Values.service.resources.limits.memory }}"

          env:
            - name: ASPNETCORE_URLS
              value: "http://+:{{.Values.service.port}}"
            {{ if .Values.service.isGateway }}
            - name: RATINGS_HOST
              value: rating-service:8050
            - name: LIBRARY_HOST
              value: library-service:8060
            - name: RESERVATIONS_HOST
              value: reservation-service:8070
            {{- end}}
            {{ if .Values.service.database.name }}
            - name: DATABASE
              value: "{{ .Values.service.database.name }}"
            {{- end }}
            - name: DB_HOST
              value: "{{ .Values.service.database.host }}"
            - name: DB_PORT
              value: "{{ .Values.service.database.port }}"
            - name: USERNAME
              value: "{{ .Values.service.database.username }}"
            - name: PASSWORD
              value: "{{ .Values.service.database.password }}"
          ports:
            - name: web
              containerPort: {{ .Values.service.port }}
